version: "3.1"

services:
  django-socio-grpc:
    image: django-socio-grpc
    tty: true 
    build:
      context: .
    command: python runserver.py
    volumes:
      - .:/opt/code
      - ./test_utils:/opt/code
    # ports:
      # - "7000:80"