jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry build
      - run: poetry config pypi-token.pypi $PYPI_TOKEN
      - run: poetry publish
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
              - CI/automatiseDeployement